version: '3'

services:

  javamelody:
    image: javamelody
    ports:
      - 1338:1337

  postgres:
    image: library/postgres:12.6
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=javamelodydb
    ports:
    - 5434:5432

  tomcat:
    image: tomcat
    ports:
      - 8090:8080
